language: java
jdk:
  - oraclejdk8

script:
- cd himock
- mvn clean test | egrep -v ' Download(ing|ed): '
- mvn install | egrep -v ' Download(ing|ed): '
- cd ..
- cd examples
- mvn clean test | egrep -v ' Download(ing|ed): '
- cd ..
